### ISSUE TITLE
UPDATE-1

### ISSUE THREAD

**Issue by Lopner** [MyNika01/telegram-bot-combat-simulator#1]
https://github.com/MyNika01/telegram-bot-combat-simulator/blob/5658898e7e237fa8f8b20a85b3e285635cee6f88/src/main/java/demo/telegrambotcombatsimulator/service/CombatService.java#L265

Вынести в метод в классе Player (передавать только необходимые параметры в новый метод)

**Comment by MyNika01** [comment]
Проблема решена
Ознакомиться можно здесь - https://github.com/MyNika01/telegram-bot-combat-simulator/commit/1c3a89122e5c25edf68bba3d812cd90c8559fb17#diff-9c6db1f4e04f7e0bf2451c57be942c094e340551eb8080037e14e158c229e763
